name: ML CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow pytest flake8 autopep8
      
      - name: Auto-format code
        run: autopep8 --in-place --recursive src

      - name: Lint code
        run: flake8 src/ || echo "⚠️ Lint warnings found, skipping failure"
      
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/

      - name: Train Random Forest model
        run: |
          python -m src.training.train_rf_mlflow --n_estimators 350 --max_depth 15

      - name: List repository files
        run: ls -la
      
      - name: Set up MLflow
        run: |
          pip install mlflow

      - name: Run MLflow experiment
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          mlflow run . -e forest -P n_estimators=350 -P max_depth=15
